services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Containerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      - ..:/workspace:cached
      - nix:/nix
    security_opt:
      - label:disable

volumes:
  nix:
